# Generated by Django 6.0.4 on 2026-05-28 20:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import mmk_panel.apps.collectibles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("nickname", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "default_sprite",
                    models.ImageField(
                        upload_to=mmk_panel.apps.collectibles.models.card_sprite_upload_to
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=mmk_panel.apps.collectibles.models.card_audio_upload_to,
                    ),
                ),
                ("health", models.PositiveIntegerField()),
                ("defense", models.PositiveIntegerField()),
                ("base_move_energy", models.PositiveIntegerField()),
                ("base_move_energy_gain", models.PositiveIntegerField()),
                ("desperation", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("cost", models.PositiveIntegerField(blank=True, null=True)),
                ("damage", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "self_defense_multiplier",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "self_attack_multiplier",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "self_move_energy_multiplier",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "self_move_energy_gain_multiplier",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "self_desperation_multiplier",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "self_defense_scalar_boost",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "self_attack_scalar_boost",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "self_move_energy_scalar_boost",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "self_move_energy_gain_scalar_boost",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "self_poison",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "self_prevent_move",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("self_custom_dialogue", models.TextField(blank=True, null=True)),
                (
                    "enemy_defense_multiplier",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "enemy_attack_multiplier",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "enemy_move_energy_multiplier",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "enemy_move_energy_gain_multiplier",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "enemy_desperation_multiplier",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "enemy_defense_scalar_boost",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "enemy_attack_scalar_boost",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "enemy_move_energy_scalar_boost",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "enemy_move_energy_gain_scalar_boost",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "enemy_desperation_scalar_boost",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "enemy_poison",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), blank=True, null=True, size=2
                    ),
                ),
                (
                    "enemy_prevent_move",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("enemy_custom_dialogue", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("desperation_constant", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name_plural": "Rarities",
            },
        ),
        migrations.CreateModel(
            name="CardMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sprite",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=mmk_panel.apps.collectibles.models.move_sprite_upload_to,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collectibles.card",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collectibles.move",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="rarity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="collectibles.rarity"
            ),
        ),
    ]
