# Generated by Django 6.0.4 on 2026-05-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectibles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rarity",
            name="weight",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
