# Generated by Django 6.0.4 on 2026-05-30 21:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collectibles", "0002_rarity_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="rarity",
            name="plate_color",
            field=colorfield.fields.ColorField(
                default="#FFFFFF", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
